### ISSUE TITLE
Information required on a Netherlands FOI request

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/wob-knop-theme#28]
From helping with the LIE investigation we think we've identified some information which always needs to be included in an FOI request in the Netherlands:

Ik, [name of requester], [role of requester] werkzaam bij [type of organisation, name of organisation]  in Nederland,
verzoek mij een kopie van de documenten met de volgende informatie te verstrekken:

[Reason for wanting the information and statement that release is in the public interest]

[Address and telephone number of the individual]

Liset can confirm if this is correct!

**Comment by LisetHamming** [comment]
Hi Jen, sorry for my late reply. An important sentence to include for FOI requests in The Netherlands is:

- 'Met een beroep op de Wet openbaarheid van bestuur (hierna: Wob) verzoek ik, [name], [journalist if you want to state so], [on behalf of an (news)organisation if that is the case] om openbaarmaking van hieronder nader te specificeren informatie bij of onder u.'

Meaning you state that this is an FOI, your name, whether you are requesting on behalf of an organisation if that is the case and then you need to be able to show a permission too and last but not least we say 'bij of onder u' referring to the fact that the documents might not be at this specific authority but at an authority for which this authority is responsible.

- 'De bestuurlijke aangelegenheid waarover ik informatie vraag, is uw beleid alsmede de concrete toepassing van uw beleid met betrekking tot: [the subject that is part of the authority's responsibility]

Stating what subject/responsibility the request is about. It is debated whether this is a legal requirement or not, but I would recommend to (therefore) always state this, also if you are not completely sure what the official task ('bestuurlijke aangelegenheid') is. That itself is not such a problem.

- no reason or importance is needed
- no address is needed when filed digitally (which is not always possible, yet) and/or no phone number is needed, although the authority might ask for it and of course needs your address if you file via normal mail because otherwise they cannot send you the documents

There are many more smart paragraphs to add, which can be read and copied at http://wob-generator.nl but this covers the essentials!

Let me know when not clear.

Groet,
Liset
